# Code generated by 'go generate'; DO NOT EDIT.
# 2024-06-04 12:09:20.3717435 +0200 CEST m=+0.026435301
#
# Data source: https://www.iso20022.org/sites/default/files/ISO10383_MIC/ISO10383_MIC.csv
# Data source publication date: 10-May-2021
#
# Provides a set of predefined ISO 10383 Market Identifier Codes
# generated from data from https://www.iso20022.org/market-identifier-codes
# with data publication date 10-May-2021.
#
# Included: MICs for countries with ISO 3166 alpha-2 codes
# AE, AL, AM, AO, AR, AT, AU, AZ, BA, BB, BD, BE, BG, BH, BM, BO, BR, BS, BW, BY, CA, CH, CI, CL, CM, CN, CO, CR, CV, CW, CY, CZ, DE, DK, DO, DZ, EC, EE, EG, ES, FI, FJ, FO, FR, GB, GE, GG, GH, GI, GR, GT, GY, HK, HN, HR, HU, ID, IE, IL, IN, IQ, IR, IS, IT, JM, JO, JP, KE, KG, KH, KN, KR, KW, KY, KZ, LA, LB, LI, LK, LT, LU, LV, LY, MA, MD, ME, MG, MK, MN, MT, MU, MV, MW, MX, MY, MZ, NA, NG, NI, NL, NO, NP, NZ, OM, PA, PE, PG, PH, PK, PL, PS, PT, PY, QA, RO, RS, RU, RW, SA, SC, SD, SE, SG, SI, SK, SV, SY, SZ, TH, TN, TR, TT, TW, TZ, UA, UG, US, UY, UZ, VC, VE, VN, VU, ZA, ZM, ZW, ZZ
# Excluded: MICs for countries with ISO 3166 alpha-2 codes
# none

_mics = {}
_mics_operational = {}

class MIC:
    """MIC is a Market Identifier Code according to ISO 10383.

    See https://www.iso20022.org/market-identifier-codes

    Parameters
    ----------
    mic : str
        The MIC. May be either an operational MIC (exchange) or a segment MIC (market).
        
        A market segment MIC is a MIC which operates in specific instruments.
        Each market segment MIC has a parent MIC which is called the “operating MIC”.
    operational_mic : str
        The operational MIC related to this market segment MIC.
        This is an operatonal MIC if it is not a market segment.
    country_code : str
        The ISO 3166 alpha-2 country code.
    time_zone_seconds : int
        The time zone offset in seconds from UTC.
    """

    def __init__(self, mic: str, operational_mic: str, country_code: str, time_zone_seconds: int) -> None:
        self.mic = mic
        self.operational_mic = operational_mic
        self.country_code = country_code
        self.time_zone_seconds = time_zone_seconds
        if mic in _mics:
            raise ValueError(f'MIC {mic} is already defined')
        _mics[mic] = self
        if mic == operational_mic:
            return
        if operational_mic in _mics_operational:
            _mics_operational[operational_mic].append(self)
        else:
            _mics_operational[operational_mic] = [self]

    def get_segments(self):
        """
        Gets all segments for this operational MIC.
        If this mic is not operational one, the segments
        of it's operational MIC are returned.
        """
        return _mics_operational[self.operational_mic]

    def __eq__(self, other) -> bool:
        """Checks if two MICs are equal.

        Parameters
        ----------
        other : `Any`
            The MIC being compared.

        Returns
        -------
        bool
            Whether the MICs are equal.
        """
        if not isinstance(other, MIC):
            return False
        if self.mic != other.mic:
            return False
        if self.operational_mic != other.operational_mic:
            return False
        if self.country_code != other.country_code:
            return False
        if self.time_zone_seconds != other.time_zone_seconds:
            return False
        return True

    def __ne__(self, other) -> bool:
        """Checks if two MICs are not equal.

        Parameters
        ----------
        other : `Any`
            The MIC being compared.

        Returns
        -------
        bool
            Whether the MICs are not equal.
        """
        return not self.__eq__(other)

    def __hash__(self):
        return hash(self.mic)

    def __str__(self):
        return str(self.mic)

    def __repr__(self):
        attributes = ['mic', 'operational_mic', 'country_code', 'time_zone_seconds']
        attr_strings = [f'{attr}={getattr(self, attr)}' for attr in attributes ]
        return 'Instrument(' + ', '.join(attr_strings) + ')'

class SubscriptableType(type):
    def __getitem__(cls, key):
        return cls.__getitem__(key)
    
class MICs(metaclass=SubscriptableType):

    @classmethod
    def __getitem__(cls, key: str) -> MIC:
        """Gets a MIC by its mic."""
        try:
            return _mics[key]
        except KeyError:
            raise KeyError(f'MIC {key} is not defined')

    XXXX = MIC('XXXX', 'XXXX', 'ZZ', 0)
    """XXXX - operational: NO MARKET (E.G. UNLISTED)."""
    XOFF = MIC('XOFF', 'XOFF', 'ZZ', 0)
    """XOFF - operational: OFF-EXCHANGE TRANSACTIONS - LISTED INSTRUMENTS. MIC TO USE FOR OFF-EXCHANGE TRANSACTIONS IN LISTED INSTRUMENTS."""

    # -------- Austria ------------------------------------
    XWBO = MIC('XWBO', 'XWBO', 'AT', 3600)
    """XWBO - operational: WIENER BOERSE AG. Location: Austria (AT), Vienna, www.wienerboerse.at."""
    EXAA = MIC('EXAA', 'XWBO', 'AT', 3600)
    """EXAA - segment of XWBO: WIENER BOERSE AG, AUSTRIAN ENERGY EXCHANGE. Location: Austria (AT), Vienna, www.exaa.at."""
    WBDM = MIC('WBDM', 'XWBO', 'AT', 3600)
    """WBDM - segment of XWBO: WIENER BOERSE AG DRITTER MARKT (THIRD MARKET). Location: Austria (AT), Vienna, www.wienerboerse.at."""
    WBAH = MIC('WBAH', 'XWBO', 'AT', 3600)
    """WBAH - segment of XWBO: WIENER BOERSE AG AMTLICHER HANDEL (OFFICIAL MARKET). Location: Austria (AT), Vienna, www.wienerboerse.at."""
    XVIE = MIC('XVIE', 'XWBO', 'AT', 3600)
    """XVIE - segment of XWBO: WIENER BOERSE AG, WERTPAPIERBOERSE (SECURITIES EXCHANGE). Location: Austria (AT), Vienna, www.wienerborse.at."""
    # -------- Belgium ------------------------------------
    XBRU = MIC('XBRU', 'XBRU', 'BE', 3600)
    """XBRU - operational: EURONEXT - EURONEXT BRUSSELS. Location: Belgium (BE), Brussels, www.euronext.com."""
    ALXB = MIC('ALXB', 'XBRU', 'BE', 3600)
    """ALXB - segment of XBRU: EURONEXT GROWTH BRUSSELS. Location: Belgium (BE), Brussels, www.euronext.com."""
    MLXB = MIC('MLXB', 'XBRU', 'BE', 3600)
    """MLXB - segment of XBRU: EURONEXT ACCESS BRUSSELS. Location: Belgium (BE), Brussels, www.euronext.com."""
    TNLB = MIC('TNLB', 'XBRU', 'BE', 3600)
    """TNLB - segment of XBRU: EURONEXT - TRADING FACILITY BRUSSELS. Location: Belgium (BE), Brussels, www.euronext.com."""
    VPXB = MIC('VPXB', 'XBRU', 'BE', 3600)
    """VPXB - segment of XBRU: EURONEXT - VENTES PUBLIQUES BRUSSELS. Location: Belgium (BE), Brussels, www.euronext.com."""
    XBRD = MIC('XBRD', 'XBRU', 'BE', 3600)
    """XBRD - segment of XBRU: EURONEXT - EURONEXT BRUSSELS - DERIVATIVES. Location: Belgium (BE), Brussels, www.euronext.com."""
    TNLK = MIC('TNLK', 'XBRU', 'BE', 3600)
    """TNLK - segment of XBRU: EURONEXT BLOCKS. MULTILATERAL TRADING FACILITY (MTF) FOR BLOCKS. Location: Belgium (BE), Brussels, www.euronext.com."""
    # -------- Denmark ----------------------
    XCSE = MIC('XCSE', 'XCSE', 'DK', 3600)
    """XCSE - operational: NASDAQ COPENHAGEN A/S. Location: Denmark (DK), Copenhagen, www.nasdaqomxnordic.com."""
    DCSE = MIC('DCSE', 'XCSE', 'DK', 3600)
    """DCSE - segment of XCSE: NASDAQ COPENHAGEN A/S - NORDIC@MID. NORDIC@MID DARK POOL FOR XCSE. Location: Denmark (DK), Copenhagen, www.nasdaqomxnordic.com."""
    DSME = MIC('DSME', 'XCSE', 'DK', 3600)
    """DSME - segment of XCSE: FIRST NORTH DENMARK -SME GROWTH MARKET. Location: Denmark (DK), Copenhagen, www.nasdaqomxnordic.com."""
    MCSE = MIC('MCSE', 'XCSE', 'DK', 3600)
    """MCSE - segment of XCSE: NASDAQ COPENHAGEN A/S – AUCTION ON DEMAND. Location: Denmark (DK), Copenhagen, www.nasdaqomxnordic.com."""
    MNDK = MIC('MNDK', 'XCSE', 'DK', 3600)
    """MNDK - segment of XCSE: FIRST NORTH DENMARK – AUCTION ON DEMAND. Location: Denmark (DK), Copenhagen, www.nasdaqomxnordic.com."""
    FNDK = MIC('FNDK', 'XCSE', 'DK', 3600)
    """FNDK - segment of XCSE: FIRST NORTH DENMARK. FIRST NORTH IS OPERATED BY NASDAQ. FIRST NORTH IS A NORDIC ALTERNATIVE MTF MARKETPLACE FOR TRADING SHARES AND OTHER TYPES OF FINANCIAL INSTRUMENTS. Location: Denmark (DK), Copenhagen, www.nasdaqomxnordic.com."""
    DNDK = MIC('DNDK', 'XCSE', 'DK', 3600)
    """DNDK - segment of XCSE: FIRST NORTH DENMARK - NORDIC@MID. NORDIC@MID DARK POOL FOR FIRST NORTH DENMARK. Location: Denmark (DK), Copenhagen, www.nasdaqomxnordic.com."""
    # -------- Finland ------------------------------------
    XNOR = MIC('XNOR', 'XNOR', 'FI', 7200)
    """XNOR - operational: NORDEA - SYSTEMATIC INTERNALISER. Location: Finland (FI), Helsinki, www.nordea.com."""
    XHEL = MIC('XHEL', 'XHEL', 'FI', 7200)
    """XHEL - operational: NASDAQ HELSINKI LTD. Location: Finland (FI), Helsinki, www.nasdaqomxnordic.com."""
    MNFI = MIC('MNFI', 'XHEL', 'FI', 7200)
    """MNFI - segment of XHEL: FIRST NORTH FINLAND – AUCTION ON DEMAND. Location: Finland (FI), Helsinki, www.nasdaqomxnordic.com."""
    DHEL = MIC('DHEL', 'XHEL', 'FI', 7200)
    """DHEL - segment of XHEL: NASDAQ HELSINKI LTD - NORDIC@MID. NORDIC@MID DARK POOL FOR XHEL. Location: Finland (FI), Helsinki, www.nasdaqomxnordic.com."""
    DNFI = MIC('DNFI', 'XHEL', 'FI', 7200)
    """DNFI - segment of XHEL: FIRST NORTH FINLAND - NORDIC@MID. NORDIC@MID DARK POOL FOR FIRST NORTH FINLAND. Location: Finland (FI), Helsinki, www.nasdaqomxnordic.com."""
    FSME = MIC('FSME', 'XHEL', 'FI', 7200)
    """FSME - segment of XHEL: FIRST NORTH FINLAND - SME GROWTH MARKET. Location: Finland (FI), Helsinki, www.nasdaqomxnordic.com."""
    FNFI = MIC('FNFI', 'XHEL', 'FI', 7200)
    """FNFI - segment of XHEL: FIRST NORTH FINLAND. FIRST NORTH IS OPERATED BY NASDAQ. FIRST NORTH IS A NORDIC ALTERNATIVE MTF MARKETPLACE FOR TRADING SHARES AND OTHER TYPES OF FINANCIAL INSTRUMENTS. Location: Finland (FI), Helsinki, www.nasdaqomxnordic.com."""
    MHEL = MIC('MHEL', 'XHEL', 'FI', 7200)
    """MHEL - segment of XHEL: NASDAQ HELSINKI LTD –  AUCTION ON DEMAND. Location: Finland (FI), Helsinki, www.nasdaqomxnordic.com."""
    # -------- France -------------------------------------
    XPAR = MIC('XPAR', 'XPAR', 'FR', 3600)
    """XPAR - operational: EURONEXT - EURONEXT PARIS. Location: France (FR), Paris, www.euronext.com."""
    XAPA = MIC('XAPA', 'XPAR', 'FR', 3600)
    """XAPA - segment of XPAR: EURONEXT - APA. APPROVED PUBLICATION ARRANGEMENT. Location: France (FR), Paris, www.euronext.com."""
    MTCH = MIC('MTCH', 'XPAR', 'FR', 3600)
    """MTCH - segment of XPAR: BONDMATCH. FINANCIAL, CORPORATE AND COVERED BONDS TRADING PLATFORM FOR PROFESSIONAL INVESTORS. Location: France (FR), Paris, www.euronext.com."""
    XMAT = MIC('XMAT', 'XPAR', 'FR', 3600)
    """XMAT - segment of XPAR: EURONEXT PARIS MATIF. Location: France (FR), Paris, www.euronext.com."""
    XMLI = MIC('XMLI', 'XPAR', 'FR', 3600)
    """XMLI - segment of XPAR: EURONEXT ACCESS PARIS. Location: France (FR), Paris, www.euronext.com."""
    ALXP = MIC('ALXP', 'XPAR', 'FR', 3600)
    """ALXP - segment of XPAR: EURONEXT GROWTH PARIS. Location: France (FR), Paris, www.euronext.com."""
    XBLK = MIC('XBLK', 'XPAR', 'FR', 3600)
    """XBLK - segment of XPAR: EURONEXT BLOCK 2. Location: France (FR), Paris, www.euronext.com."""
    XETF = MIC('XETF', 'XPAR', 'FR', 3600)
    """XETF - segment of XPAR: EURONEXT ETF ACCESS. Location: France (FR), Paris, www.euronext.com."""
    XMON = MIC('XMON', 'XPAR', 'FR', 3600)
    """XMON - segment of XPAR: EURONEXT PARIS MONEP. Location: France (FR), Paris, www.euronext.com."""
    XSPM = MIC('XSPM', 'XPAR', 'FR', 3600)
    """XSPM - segment of XPAR: EURONEXT STRUCTURED PRODUCTS MTF. MULTILATERAL TRADING FACILITY FOR THE TRADING OF STRUCTURED PRODUCTS. Location: France (FR), Paris, www.euronext.com."""
    # -------- Germany ------------------------------------
    CATS = MIC('CATS', 'CATS', 'DE', 3600)
    """CATS - operational: CATS. ELECTRONIC TRADING PLATFORM FOR STRUCTURED PRODUCTS. THE OWNER OF CATS HAS CHANGED FROM CITIGROUP TO BOERSE STUTTGART. Location: Germany (DE), Frankfurt, www.bs-cats.com."""
    XECB = MIC('XECB', 'XECB', 'DE', 3600)
    """XECB - operational: ECB EXCHANGE RATES. EURO FOREIGN EXCHANGE REFERENCE RATES. Location: Germany (DE), Frankfurt, www.ecb.europa.eu."""
    XEUR = MIC('XEUR', 'XEUR', 'DE', 3600)
    """XEUR - operational: EUREX DEUTSCHLAND. Location: Germany (DE), Frankfurt, www.eurexchange.com."""
    XETR = MIC('XETR', 'XETR', 'DE', 3600)
    """XETR - operational: XETRA. Location: Germany (DE), Frankfurt, www.deutsche-boerse.com."""
    XETA = MIC('XETA', 'XETR', 'DE', 3600)
    """XETA - segment of XETR: XETRA - REGULIERTER MARKT. Location: Germany (DE), Frankfurt, www.deutsche-boerse.com."""
    XETB = MIC('XETB', 'XETR', 'DE', 3600)
    """XETB - segment of XETR: XETRA - FREIVERKEHR. Location: Germany (DE), Frankfurt, www.deutsche-boerse.com."""
    XETW = MIC('XETW', 'XETR', 'DE', 3600)
    """XETW - segment of XETR: XETRA – SCALE – OFF-BOOK. Location: Germany (DE), Frankfurt, www.deutsche-boerse.com."""
    XETV = MIC('XETV', 'XETR', 'DE', 3600)
    """XETV - segment of XETR: XETRA – FREIVERKEHR– OFF-BOOK. Location: Germany (DE), Frankfurt, www.deutsche-boerse.com."""
    XETU = MIC('XETU', 'XETR', 'DE', 3600)
    """XETU - segment of XETR: XETRA – REGULIERTERMARKT – OFF-BOOK. Location: Germany (DE), Frankfurt, www.deutsche-boerse.com."""
    XETS = MIC('XETS', 'XETR', 'DE', 3600)
    """XETS - segment of XETR: XETRA - SCALE. XETRA SME GROWTH MARKET. Location: Germany (DE), Frankfurt, www.deutsche-boerse.com."""
    # -------- Hungary ------------------------------------
    XBUD = MIC('XBUD', 'XBUD', 'HU', 3600)
    """XBUD - operational: BUDAPEST STOCK EXCHANGE. Location: Hungary (HU), Budapest, www.bet.hu."""
    BETA = MIC('BETA', 'XBUD', 'HU', 3600)
    """BETA - segment of XBUD: BETA MARKET. LAUNCHED IN NOVEMBER 2011,  MULTILATERAL TRADING FACILITY. Location: Hungary (HU), Budapest, www.bse.hu."""
    XBND = MIC('XBND', 'XBUD', 'HU', 3600)
    """XBND - segment of XBUD: BUDAPEST STOCK EXCHANGE - XBOND. DEDICATED MARKET FOR BONDS. Location: Hungary (HU), Budapest, www.bet.hu."""
    XTND = MIC('XTND', 'XBUD', 'HU', 3600)
    """XTND - segment of XBUD: XTEND. BUDAPEST STOCK EXCHANGE MULTILATERAL TRADING FACILITY (MTF). Location: Hungary (HU), Budapest, www.bet.hu."""
    # -------- Iceland ------------------------------------
    XICE = MIC('XICE', 'XICE', 'IS', 0)
    """XICE - operational: NASDAQ ICELAND HF. Location: Iceland (IS), Reykjavik, www.nasdaqomxnordic.com."""
    DICE = MIC('DICE', 'XICE', 'IS', 0)
    """DICE - segment of XICE: NASDAQ ICELAND HF. - NORDIC@MID. NORDIC@MID DARK POOL FOR XICE. Location: Iceland (IS), Reykjavik, www.nasdaqomxnordic.com."""
    FNIS = MIC('FNIS', 'XICE', 'IS', 0)
    """FNIS - segment of XICE: FIRST NORTH ICELAND. FIRST NORTH IS OPERATED BY NASDAQ. FIRST NORTH IS A NORDIC ALTERNATIVE MTF MARKETPLACE FOR TRADING SHARES AND OTHER TYPES OF FINANCIAL INSTRUMENTS. Location: Iceland (IS), Reykjavik, www.nasdaqomxnordic.com."""
    DNIS = MIC('DNIS', 'XICE', 'IS', 0)
    """DNIS - segment of XICE: FIRST NORTH ICELAND - NORDIC@MID. NORDIC@MID DARK POOL FOR FIRST NORTH ICELAND. Location: Iceland (IS), Reykjavik, www.nasdaqomxnordic.com."""
    MNIS = MIC('MNIS', 'XICE', 'IS', 0)
    """MICE - segment of XICE: NASDAQ ICELAND HF. – AUCTION ON DEMAND. Location: Iceland (IS), Reykjavik, www.nasdaqomxnordic.com."""
    # -------- Ireland ------------------------------------
    XDUB = MIC('XDUB', 'XDUB', 'IE', 0)
    """XDUB - operational: IRISH STOCK EXCHANGE - ALL MARKET. Location: Ireland (IE), Dublin, www.ise.ie."""
    XMSM = MIC('XMSM', 'XDUB', 'IE', 0)
    """XMSM - segment of XDUB: EURONEXT DUBLIN. Location: Ireland (IE), Dublin, www.ise.ie."""
    XEYE = MIC('XEYE', 'XDUB', 'IE', 0)
    """XEYE - segment of XDUB: IRISH STOCK EXCHANGE  - GLOBAL EXCHANGE MARKET. Location: Ireland (IE), Dublin, www.ise.ie."""
    EDBT = MIC('EDBT', 'XDUB', 'IE', 0)
    """EDBT - segment of XDUB: EURONEXT DUBLIN - TRADED BONDS. Location: Ireland (IE), Dublin, www.euronext.com."""
    EDGL = MIC('EDGL', 'XDUB', 'IE', 0)
    """EDGL - segment of XDUB: GLOBAL EXCHANGE MARKET - TRADED BONDS. Location: Ireland (IE), Dublin, www.euronext.com."""
    XATL = MIC('XATL', 'XDUB', 'IE', 0)
    """XATL - segment of XDUB: ATLANTIC SECURITIES MARKET. ATLANTIC SECURITIES MARKET (ASM). THE ASM IS AUTHORISED BY THE CENTRAL BANK OF IRELAND AS A MTF AND IS REGULATED BY THE IRISH STOCK EXCHANGE PLC. Location: Ireland (IE), Dublin, www.ise.ie."""
    XESM = MIC('XESM', 'XDUB', 'IE', 0)
    """XESM - segment of XDUB: EURONEXT GROWTH DUBLIN. Location: Ireland (IE), Dublin, www.ise.ie."""
    # -------- Italy --------------------------------------
    XMIL = MIC('XMIL', 'XMIL', 'IT', 3600)
    """XMIL - operational: BORSA ITALIANA S.P.A. Location: Italy (IT), Milano, www.borsaitaliana.it."""
    XDMI = MIC('XDMI', 'XMIL', 'IT', 3600)
    """XDMI - segment of XMIL: ITALIAN DERIVATIVES MARKET. Location: Italy (IT), Milan, www.borsaitaliana.it."""
    XMOT = MIC('XMOT', 'XMIL', 'IT', 3600)
    """XMOT - segment of XMIL: EXTRAMOT. MTF OF BONDS MANAGED AND ORGANISED BY BORSA ITALIANA. Location: Italy (IT), Milano, www.borsaitaliana.it."""
    ETLX = MIC('ETLX', 'XMIL', 'IT', 3600)
    """ETLX - segment of XMIL: EUROTLX. Location: Italy (IT), Milano, www.eurotlx.com."""
    MTAH = MIC('MTAH', 'XMIL', 'IT', 3600)
    """MTAH - segment of XMIL: BORSA ITALIANA EQUITY MTF. SINCE 11.7.16, BIEM OFFERS TRADING IN REGULAR MARKET HOURS FOR INTERNATIONAL SHARES ("BIT GEM" SEGMENT, FROM 8AM TO 5:42PM MILAN TIME) AND "AFTER HOUR" TRADING FOR ITALIAN AND INTL. SHARES ("TAH" SEGMENT, FROM 6PM TO 8:30PM MILAN TIME). Location: Italy (IT), Milan, www.borsaitaliana.it."""
    ATFX = MIC('ATFX', 'XMIL', 'IT', 3600)
    """ATFX - segment of XMIL: ATFUND MTF. MULTILATERAL TRADING FACILITY FOR OPEN END FUNDS. Location: Italy (IT), Milano, www.borsaitaliana.it."""
    XAIM = MIC('XAIM', 'XMIL', 'IT', 3600)
    """XAIM - segment of XMIL: AIM ITALIA - MERCATO ALTERNATIVO DEL CAPITALE. MULTILATERAL TRADING FACILITY - MERGE OF AIM ITALIA AND MAC, MAC WILL BE OPENED TILL END 2012. Location: Italy (IT), Milan, www.borsaitaliana.it."""
    MOTX = MIC('MOTX', 'XMIL', 'IT', 3600)
    """MOTX - segment of XMIL: ELECTRONIC BOND MARKET. Location: Italy (IT), Milano, www.borsaitaliana.it."""
    ETFP = MIC('ETFP', 'XMIL', 'IT', 3600)
    """ETFP - segment of XMIL: ELECTRONIC ETF, ETC/ETN AND OPEN-END FUNDS MARKET. Location: Italy (IT), Milano, www.borsaitaliana.it."""
    MIVX = MIC('MIVX', 'XMIL', 'IT', 3600)
    """MIVX - segment of XMIL: MARKET FOR INVESTMENT VEHICLES. THE MIV, DEDICATED TO INVESTMENT VEHICLES, IS DIVIDED INTO THREE SEGMENTS: UNITS OF CLOSED-END FUNDS SEGMENT, INVESTMENT COMPANIES SEGMENT, REAL ESTATE INVESTMENT COMPANIES SEGMENT (REICS FROM THE EXPANDI MARKET). Location: Italy (IT), Milan, www.borsaitaliana.it."""
    MTAA = MIC('MTAA', 'XMIL', 'IT', 3600)
    """MTAA - segment of XMIL: ELECTRONIC SHARE MARKET. Location: Italy (IT), Milan, www.borsaitaliana.it."""
    SEDX = MIC('SEDX', 'XMIL', 'IT', 3600)
    """SEDX - segment of XMIL: SECURITISED DERIVATIVES MARKET. MULTILATERAL TRADING FACILITY. Location: Italy (IT), Milano, www.borsaitaliana.it."""
    # -------- Luxembourg ---------------------------------
    XLUX = MIC('XLUX', 'XLUX', 'LU', 3600)
    """XLUX - operational: LUXEMBOURG STOCK EXCHANGE. Location: Luxembourg (LU), Luxembourg, www.bourse.lu."""
    EMTF = MIC('EMTF', 'XLUX', 'LU', 3600)
    """EMTF - segment of XLUX: EURO MTF. Location: Luxembourg (LU), Luxembourg, www.bourse.lu."""
    # -------- Norway -------------------------------------
    XOSL = MIC('XOSL', 'XOSL', 'NO', 3600)
    """XOSL - operational: OSLO BORS. Location: Norway (NO), Oslo, www.oslobors.no."""
    XOAS = MIC('XOAS', 'XOSL', 'NO', 3600)
    """XOAS - segment of XOSL: EURONEXT EXPAND OSLO. Location: Norway (NO), Oslo, www.oslobors.no."""
    XOSC = MIC('XOSC', 'XOSL', 'NO', 3600)
    """XOSC - segment of XOSL: OSLO CONNECT. MULTILATERAL TRADING FACILITY FOR FINANCIAL INSTRUMENTS. Location: Norway (NO), Oslo, www.oslobors.no."""
    XOBD = MIC('XOBD', 'XOSL', 'NO', 3600)
    """XOBD - segment of XOSL: OSLO BORS - DERIVATIVES MARKET. Location: Norway (NO), Oslo, www.oslobors.no."""
    XOAM = MIC('XOAM', 'XOSL', 'NO', 3600)
    """XOAM - segment of XOSL: NORDIC ALTERNATIVE BOND MARKET. NORDIC MARKETPLACE FOR LISTING OF BONDS. Location: Norway (NO), Oslo, www.oslobors.no."""
    XOSA = MIC('XOSA', 'XOSL', 'NO', 3600)
    """XOSA - segment of XOSL: OSLO BORS - LIT X AUCTIONS. Location: Norway (NO), Oslo, www.oslobors.no."""
    MERD = MIC('MERD', 'XOSL', 'NO', 3600)
    """MERD - segment of XOSL: MERKUR MARKET - DARK POOL. MULTILATERAL TRADING FACILITY FOR FINANCIAL INSTRUMENTS - DARK POOL. Location: Norway (NO), Oslo, www.oslobors.no."""
    MERK = MIC('MERK', 'XOSL', 'NO', 3600)
    """MERK - segment of XOSL: EURONEXT GROWTH - OSLO. MULTILATERAL TRADING FACILITY FOR FINANCIAL INSTRUMENTS. Location: Norway (NO), Oslo, www.oslobors.no."""
    XOSD = MIC('XOSD', 'XOSL', 'NO', 3600)
    """XOSD - segment of XOSL: OSLO BORS NORTH SEA - DARK POOL. Location: Norway (NO), Oslo, www.oslobors.no."""
    XOAA = MIC('XOAA', 'XOSL', 'NO', 3600)
    """XOAA - segment of XOSL: OSLO BORS ASA - OSLO AXESS LIT X AUCTIONS. LISTED INSTRUMENTS. Location: Norway (NO), Oslo, www.oslobors.no."""
    NIBR = MIC('NIBR', 'XOSL', 'NO', 3600)
    """NIBR - segment of XOSL: NORWEGIAN INTER BANK OFFERED RATE. OFFICIAL PLATFORM FOR SUBMISSION OF NIBOR BASIS RATES AND DISTRIBUTION OF NIBOR FIXING RATES. Location: Norway (NO), Oslo, www.oslobors.no."""
    XOAD = MIC('XOAD', 'XOSL', 'NO', 3600)
    """XOAD - segment of XOSL: OSLO AXESS NORTH SEA - DARK POOL. Location: Norway (NO), Oslo, www.oslobors.no."""
    # -------- Poland -------------------------------------
    XWAR = MIC('XWAR', 'XWAR', 'PL', 3600)
    """XWAR - operational: WARSAW STOCK EXCHANGE/EQUITIES/MAIN MARKET. Location: Poland (PL), Warsaw, www.gpw.pl."""
    WDER = MIC('WDER', 'XWAR', 'PL', 3600)
    """WDER - segment of XWAR: WARSAW STOCK EXCHANGE/FINANCIAL DERIVATIVES. Location: Poland (PL), Warsaw, www.pochodne.gpw.pl."""
    WETP = MIC('WETP', 'XWAR', 'PL', 3600)
    """WETP - segment of XWAR: WARSAW STOCK EXCHANGE/ ETPS. Location: Poland (PL), Warsaw, www.gpw.pl."""
    WIND = MIC('WIND', 'XWAR', 'PL', 3600)
    """WIND - segment of XWAR: WARSAW STOCK EXCHANGE/INDICES. Location: Poland (PL), Warsaw, www.gpw.pl."""
    WMTF = MIC('WMTF', 'XWAR', 'PL', 3600)
    """WMTF - segment of XWAR: WARSAW STOCK EXCHANGE/BONDS/CATALYST/MTF. Location: Poland (PL), Warsaw, www.gpwcatalyst.pl."""
    WBCL = MIC('WBCL', 'XWAR', 'PL', 3600)
    """WBCL - segment of XWAR: WARSAW STOCK EXCHANGE/BONDS/CATALYST/LISTING. Location: Poland (PL), Warsaw, www.gpwcatalyst.pl."""
    WBON = MIC('WBON', 'XWAR', 'PL', 3600)
    """WBON - segment of XWAR: WARSAW STOCK EXCHANGE/ BONDS/CATALYST/MAIN MARKET. Location: Poland (PL), Warsaw, www.gpwcatalyst.pl."""
    BOSP = MIC('BOSP', 'XWAR', 'PL', 3600)
    """BOSP - segment of XWAR: WARSAW STOCK EXCHANGE/BONDS/CATALYST/BONDSPOT/MTF. MULTILATERAL TRADING FACILITIES FOR DEBT INSTRUMENTS. Location: Poland (PL), Warsaw, www.bondspot.pl."""
    RPWC = MIC('RPWC', 'XWAR', 'PL', 3600)
    """RPWC - segment of XWAR: WARSAW STOCK EXCHANGE/BONDS/CATALYST/BONDSPOT/REGULATED MARKET. Location: Poland (PL), Warsaw, www.bondspot.pl."""
    TBSP = MIC('TBSP', 'XWAR', 'PL', 3600)
    """TBSP - segment of XWAR: WARSAW STOCK EXCHANGE/BONDS/BONDSPOT/TREASURY BOND MARKET. CHANGES IN BONDSPOT OWNERSHIP STRUCTURE. THEY ARE NO LONGER IN MTS GROUP. Location: Poland (PL), Warsaw, www.bondspot.pl."""
    XNCO = MIC('XNCO', 'XWAR', 'PL', 3600)
    """XNCO - segment of XWAR: WARSAW STOCK EXCHANGE/ EQUITIES/NEW CONNECT - MTF. MARKET FINANCING THE GROWTH OF YOUNG COMPANIES WITH A LARGE GROWTH POTENTIAL, ORGANISED AND OPERATED BY THE WSE. Location: Poland (PL), Warsaw, www.newconnect.pl."""
    WIPO = MIC('WIPO', 'XWAR', 'PL', 3600)
    """WIPO - segment of XWAR: WARSAW STOCK EXCHANGE - OTHER THAN XOFF OR XXXX. ONLY FOR IPO/SPO PURPOSES. TRANSACTIONS ARE NOT SUBJECTED TO BE REPORTED TO ARM. Location: Poland (PL), Warsaw, www.wse.pl."""
    PLPD = MIC('PLPD', 'XWAR', 'PL', 3600)
    """PLPD - segment of XWAR: WARSAW STOCK EXCHANGE/POLISH POWER EXCHANGE/REGULATED MARKET. Location: Poland (PL), Warsaw, www.tge.pl."""
    PLPO = MIC('PLPO', 'XWAR', 'PL', 3600)
    """PLPO - segment of XWAR: WARSAW STOCK EXCHANGE/COMMODITIES/POLISH POWER - EXCHANGE/ORGANIZED TRADING FACILITIES. Location: Poland (PL), Warsaw, www.gpw.pl."""
    PLPS = MIC('PLPS', 'XWAR', 'PL', 3600)
    """PLPS - segment of XWAR: WARSAW STOCK EXCHANGE/COMMODITIES/POLISH POWER EXCHANGE/SPOT. Location: Poland (PL), Warsaw, www.gpw.pl."""
    TBSA = MIC('TBSA', 'XWAR', 'PL', 3600)
    """TBSA - segment of XWAR: WARSAW STOCK EXCHANGE/BONDS/TREASURY BOND/BONDSPOT/B2C MARKET/MTF. Location: Poland (PL), Warsaw, www.bondspot.pl."""
    XGLO = MIC('XGLO', 'XWAR', 'PL', 3600)
    """XGLO - segment of XWAR: WARSAW STOCK EXCHANGE/ EQUITIES/GLOBAL MARKET - MTF. MULTILATERAL TRADING FACILITY. Location: Poland (PL), Warsaw, www.gpw.pl."""
    # -------- Portugal -----------------------------------
    XLIS = MIC('XLIS', 'XLIS', 'PT', 0)
    """XLIS - operational: EURONEXT - EURONEXT LISBON. Location: Portugal (PT), Lisboa, www.euronext.com."""
    ALXL = MIC('ALXL', 'XLIS', 'PT', 0)
    """ALXL - segment of XLIS: EURONEXT GROWTH LISBON. Location: Portugal (PT), Lisbon, www.euronext.com."""
    ENXL = MIC('ENXL', 'XLIS', 'PT', 0)
    """ENXL - segment of XLIS: EURONEXT ACCESS LISBON. Location: Portugal (PT), Lisboa, www.euronext.com."""
    MFOX = MIC('MFOX', 'XLIS', 'PT', 0)
    """MFOX - segment of XLIS: EURONEXT - MERCADO DE FUTUROS E OPÇÕES. Location: Portugal (PT), Lisboa, www.euronext.com."""
    WQXL = MIC('WQXL', 'XLIS', 'PT', 0)
    """WQXL - segment of XLIS: EURONEXT - MARKET WITHOUT QUOTATIONS LISBON. Location: Portugal (PT), Lisboa, www.euronext.com."""
    # -------- Spain ------------------------------------
    BMEX = MIC('BMEX', 'BMEX', 'ES', 3600)
    """BMEX - operational: BME - BOLSAS Y MERCADOS ESPANOLES. Location: Spain (ES), Madrid, www.bolsasymercados.es."""
    MABX = MIC('MABX', 'BMEX', 'ES', 3600)
    """MABX - segment of BMEX: BME MTF EQUITY (IIC AND ECR SEGMENTS). Location: Spain (ES), Madrid, www.bmegrowth.es."""
    SEND = MIC('SEND', 'BMEX', 'ES', 3600)
    """SEND - segment of BMEX: SEND - SISTEMA ELECTRONICO DE NEGOCIACION DE DEUDA. SEND IS AN ELECTRONIC TRADING PLATFORM, DEVELOPED BY AIAF MERCADO DE RENTA FIJA, DESIGNED FOR THE TRADING OF RETAIL DISTRIBUTED FIXED INCOME SECURITIES LISTED IN THIS MARKET. Location: Spain (ES), Madrid, www.aiaf.es."""
    XBAR = MIC('XBAR', 'BMEX', 'ES', 3600)
    """XBAR - segment of BMEX: BOLSA DE BARCELONA. Location: Spain (ES), Barcelona, www.borsabcn.es."""
    XBIL = MIC('XBIL', 'BMEX', 'ES', 3600)
    """XBIL - segment of BMEX: BOLSA DE VALORES DE BILBAO. Location: Spain (ES), Bilbao, www.bolsabilbao.es."""
    XDRF = MIC('XDRF', 'BMEX', 'ES', 3600)
    """XDRF - segment of BMEX: AIAF - MERCADO DE RENTA FIJA. Location: Spain (ES), Madrid, www.aiaf.es."""
    XLAT = MIC('XLAT', 'BMEX', 'ES', 3600)
    """XLAT - segment of BMEX: LATIBEX. Location: Spain (ES), Madrid, www.latibex.com."""
    XMAD = MIC('XMAD', 'BMEX', 'ES', 3600)
    """XMAD - segment of BMEX: BOLSA DE MADRID. Location: Spain (ES), Madrid, www.bolsamadrid.es."""
    XMRV = MIC('XMRV', 'BMEX', 'ES', 3600)
    """XMRV - segment of BMEX: MEFF FINANCIAL DERIVATIVES. Location: Spain (ES), Madrid, www.meff.com."""
    XVAL = MIC('XVAL', 'BMEX', 'ES', 3600)
    """XVAL - segment of BMEX: BOLSA DE VALENCIA. Location: Spain (ES), Valencia, www.bolsavalencia.es."""
    XMPW = MIC('XMPW', 'BMEX', 'ES', 3600)
    """XMPW - segment of BMEX: MEFF POWER DERIVATIVES. MEFF SEGMENT FOR THE TRADING OF POWER DERIVATIVES. Location: Spain (ES), Madrid, www.meff.com."""
    XMFX = MIC('XMFX', 'BMEX', 'ES', 3600)
    """XMFX - segment of BMEX: MEFF FX FINANCIAL DERIVATIVES. DERIVATIVES IN CURRENCIES. Location: Spain (ES), Madrid, www.meff.es."""
    SBAR = MIC('SBAR', 'BMEX', 'ES', 3600)
    """SBAR - segment of BMEX: BOLSA DE BARCELONA RENTA FIJA. ELECTRONIC TRADING PLATFORM FIXED INCOME BOLSA DE BARCELONA. Location: Spain (ES), Barcelona, www.bolsasymercados.es."""
    SBIL = MIC('SBIL', 'BMEX', 'ES', 3600)
    """SBIL - segment of BMEX: BOLSA DE BILBAO RENTA FIJA. ELECTRONIC TRADING PLATFORM FIXED INCOME BOLSA DE BILBAO. Location: Spain (ES), Bilbao, www.bolsasymercados.es."""
    MERF = MIC('MERF', 'BMEX', 'ES', 3600)
    """MERF - segment of BMEX: MERCADO ELECTRONICO DE RENTA FIJA. REGISTERED MARKET FOR BONDS ELECTRONIC TRADING PLATFORM. Location: Spain (ES), Madrid, www.bmerf.es."""
    BMCL = MIC('BMCL', 'BMEX', 'ES', 3600)
    """BMCL - segment of BMEX: BME CLEARING S.A. Location: Spain (ES), Madrid, www.aiaf.es."""
    BMEA = MIC('BMEA', 'BMEX', 'ES', 3600)
    """BMEA - segment of BMEX: BME - APA. APPROVED PUBLICATION ARRANGEMENT (APA). Location: Spain (ES), Madrid, www.bolsasymercados.es/regulatory-services/ing/home."""
    MARF = MIC('MARF', 'BMEX', 'ES', 3600)
    """MARF - segment of BMEX: MERCADO ALTERNATIVO DE RENTA FIJA. ALTERNATIVE FIXED INCOME MARKET FOR SMALL AND MEDIUM ENTERPRISES ISSUES. Location: Spain (ES), Madrid, www.aiaf.es."""
    GROW = MIC('GROW', 'BMEX', 'ES', 3600)
    """GROW - segment of BMEX: BME GROWTH MARKET. Location: Spain (ES), Madrid, www.bmegrowth.es."""
    # -------- Sweden ------------------------------------
    XSTO = MIC('XSTO', 'XSTO', 'SE', 3600)
    """XSTO - operational: NASDAQ STOCKHOLM AB. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    ESTO = MIC('ESTO', 'XSTO', 'SE', 3600)
    """ESTO - segment of XSTO: NASDAQ STOCKHOLM AB – NORWAY ETF. ELECTRONIC TRADING FACILITY (ETF). Location: Sweden (SE), Stockholm, nasdaqomxnordic.com."""
    FIED = MIC('FIED', 'XSTO', 'SE', 3600)
    """FIED - segment of XSTO: NASDAQ STOCKHOLM AB - FINNISH EQ DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    DSTO = MIC('DSTO', 'XSTO', 'SE', 3600)
    """DSTO - segment of XSTO: NASDAQ STOCKHOLM AB - NORDIC@MID. NORDIC@MID DARK POOL FOR XSTO. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    DOSE = MIC('DOSE', 'XSTO', 'SE', 3600)
    """DOSE - segment of XSTO: FIRST NORTH SWEDEN - NORWAY NORDIC@MID. Location: Sweden (SE), Stockholm, nasdaqomxnordic.com/firstnorth."""
    DNSE = MIC('DNSE', 'XSTO', 'SE', 3600)
    """DNSE - segment of XSTO: FIRST NORTH SWEDEN - NORDIC@MID. NORDIC@MID DARK POOL FOR FIRST NORTH SWEDEN. Location: Sweden (SE), Stockholm, nasdaqomxnordic.com/firstnorth."""
    EBON = MIC('EBON', 'XSTO', 'SE', 3600)
    """EBON - segment of XSTO: NASDAQ STOCKHOLM AB - EUR FI DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    NOFI = MIC('NOFI', 'XSTO', 'SE', 3600)
    """NOFI - segment of XSTO: NASDAQ STOCKHOLM AB - NORWEGIAN FI DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    MSTO = MIC('MSTO', 'XSTO', 'SE', 3600)
    """MSTO - segment of XSTO: NASDAQ STOCKHOLM AB – AUCTION ON DEMAND. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    SSME = MIC('SSME', 'XSTO', 'SE', 3600)
    """SSME - segment of XSTO: FIRST NORTH SWEDEN - SME GROWTH MARKET. Location: Sweden (SE), Stockholm, nasdaqomxnordic.com."""
    CSTO = MIC('CSTO', 'XSTO', 'SE', 3600)
    """CSTO - segment of XSTO: NASDAQ CLEARING AB. CLEARING HOUSE FOR EQUITY, FIXED INCOME AND COMMODITIES DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomx.com/europeanclearing."""
    MNSE = MIC('MNSE', 'XSTO', 'SE', 3600)
    """MNSE - segment of XSTO: FIRST NORTH SWEDEN – AUCTION ON DEMAND. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    SEED = MIC('SEED', 'XSTO', 'SE', 3600)
    """SEED - segment of XSTO: NASDAQ STOCKHOLM AB - SWEDISH EQ DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    MOSE = MIC('MOSE', 'XSTO', 'SE', 3600)
    """MOSE - segment of XSTO: FIRST NORTH SWEDEN - NORWAY AUCTION ON DEMAND. Location: Sweden (SE), Stockholm, nasdaqomxnordic.com/firstnorth."""
    DKED = MIC('DKED', 'XSTO', 'SE', 3600)
    """DKED - segment of XSTO: NASDAQ STOCKHOLM AB - DANISH EQ DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    NOED = MIC('NOED', 'XSTO', 'SE', 3600)
    """NOED - segment of XSTO: NASDAQ STOCKHOLM AB - NORWEGIAN EQ DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    XOPV = MIC('XOPV', 'XSTO', 'SE', 3600)
    """XOPV - segment of XSTO: OTC PUBLICATION VENUE. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    FNSE = MIC('FNSE', 'XSTO', 'SE', 3600)
    """FNSE - segment of XSTO: FIRST NORTH SWEDEN. FIRST NORTH IS OPERATED BY NASDAQ. FIRST NORTH IS A NORDIC ALTERNATIVE MTF MARKETPLACE FOR TRADING SHARES AND OTHER TYPES OF FINANCIAL INSTRUMENTS. Location: Sweden (SE), Stockholm, nasdaqomxnordic.com/firstnorth."""
    PNED = MIC('PNED', 'XSTO', 'SE', 3600)
    """PNED - segment of XSTO: NASDAQ STOCKHOLM AB - PAN-NORDIC EQ DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    EUWB = MIC('EUWB', 'XSTO', 'SE', 3600)
    """EUWB - segment of XSTO: NASDAQ STOCKHOLM AB - EUR WB EQ DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    USWB = MIC('USWB', 'XSTO', 'SE', 3600)
    """USWB - segment of XSTO: NASDAQ STOCKHOLM AB - USD WB EQ DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    GBWB = MIC('GBWB', 'XSTO', 'SE', 3600)
    """GBWB - segment of XSTO: NASDAQ STOCKHOLM AB – GBP WB EQ DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    DKFI = MIC('DKFI', 'XSTO', 'SE', 3600)
    """DKFI - segment of XSTO: NASDAQ STOCKHOLM AB - DANISH FI DERIVATIVES. Location: Sweden (SE), Stockholm, www.nasdaqomxnordic.com."""
    ONSE = MIC('ONSE', 'XSTO', 'SE', 3600)
    """ONSE - segment of XSTO: FIRST NORTH SWEDEN - NORWAY. Location: Sweden (SE), Stockholm, nasdaqomxnordic.com/firstnorth."""
    # -------- Switzerland --------------------------------
    XBRN = MIC('XBRN', 'XBRN', 'CH', 3600)
    """XBRN - operational: BX SWISS AG. BX WORLDCAPS, BX LOCAL SHARES. Location: Switzerland (CH), Bern, www.bxswiss.com, www.berne-x.com."""
    STOX = MIC('STOX', 'STOX', 'CH', 3600)
    """STOX - operational: STOXX LIMITED. Location: Switzerland (CH), Zurich, www.stoxx.com."""
    XSCU = MIC('XSCU', 'STOX', 'CH', 3600)
    """XSCU - segment of STOX: STOXX LIMITED - CUSTOMIZED INDICES. Location: Switzerland (CH), Zurich, www.stoxx.com."""
    XSTV = MIC('XSTV', 'STOX', 'CH', 3600)
    """XSTV - segment of STOX: STOXX LIMITED - VOLATILITY INDICES. Location: Switzerland (CH), Zurich, www.stoxx.com."""
    XSTX = MIC('XSTX', 'STOX', 'CH', 3600)
    """XSTX - segment of STOX: STOXX LIMITED - INDICES. Location: Switzerland (CH), Zurich, www.stoxx.com."""
    XSWX = MIC('XSWX', 'XSWX', 'CH', 3600)
    """XSWX - operational: SIX SWISS EXCHANGE. MID/SMALL CAP EQUITY, FUNDS, ETFS, BOND SEGMENT. WWW.SIX-GROUP.COM/EN/PRODUCTS-SERVICES/THE-SWISS-STOCK-EXCHANGE.HTML. Location: Switzerland (CH), Zurich, www.six-group.com/en/site/exchanges.html."""
    XBTR = MIC('XBTR', 'XSWX', 'CH', 3600)
    """XBTR - segment of XSWX: SIX SWISS BILATERAL TRADING PLATFORM FOR STRUCTURED OTC PRODUCTS. WWW.SIX-GROUP.COM/EN/PRODUCTS-SERVICES/THE-SWISS-STOCK-EXCHANGE.HTML. Location: Switzerland (CH), Zurich, www.six-group.com/en/site/exchanges.html."""
    XSWM = MIC('XSWM', 'XSWX', 'CH', 3600)
    """XSWM - segment of XSWX: SIX SWISS EXCHANGE - SIX SWISS EXCHANGE AT MIDPOINT. Location: Switzerland (CH), Zurich, www.six-group.com/en/site/exchanges.html."""
    XSEB = MIC('XSEB', 'XSWX', 'CH', 3600)
    """XSEB - segment of XSWX: SIX SWISS EXCHANGE - EBBO BOOK. EBBO EQUITY ORDER BOOK. WWW.SIX-GROUP.COM/EN/PRODUCTS-SERVICES/THE-SWISS-STOCK-EXCHANGE.HTML. Location: Switzerland (CH), Zurich, www.six-group.com/en/site/exchanges.html."""
    XQMH = MIC('XQMH', 'XSWX', 'CH', 3600)
    """XQMH - segment of XSWX: SIX SWISS EXCHANGE – STRUCTURED PRODUCTS. WARRANTS AND STRUCTURED PRODUCTS SEGMENT. WWW.SIX-GROUP.COM/EN/PRODUCTS-SERVICES/THE-SWISS-STOCK-EXCHANGE.HTML. Location: Switzerland (CH), Zurich, www.six-structured-products.com."""
    XSDX = MIC('XSDX', 'XSWX', 'CH', 3600)
    """XSDX - segment of XSWX: SIX DIGITAL EXCHANGE. REGULATED PLATFORM TO ISSUE AND TRADE DIGITAL ASSETS. WWW.SIX-GROUP.COM/EN/PRODUCTS-SERVICES/THE-SWISS-STOCK-EXCHANGE.HTML. Location: Switzerland (CH), Zurich, www.six-group.com/en/site/exchanges.html."""
    XQOD = MIC('XQOD', 'XSWX', 'CH', 3600)
    """XQOD - segment of XSWX: SIX SWISS EXCHANGE - ETF QOD. WWW.SIX-GROUP.COM/EN/PRODUCTS-SERVICES/THE-SWISS-STOCK-EXCHANGE.HTML. Location: Switzerland (CH), Zurich, www.six-group.com/en/site/exchanges.html."""
    XDLP = MIC('XDLP', 'XSWX', 'CH', 3600)
    """XDLP - segment of XSWX: SIX SWISS EXCHANGE - DEAL POOL - BOOK BUILDING AND ANNOUNCEMENT PLATFORM. WWW.SIX-GROUP.COM/EN/PRODUCTS-SERVICES/THE-SWISS-STOCK-EXCHANGE.HTML. Location: Switzerland (CH), Zurich, www.six-group.com/en/site/exchanges.html."""
    # -------- The Netherlands -------------------------------------
    ETPA = MIC('ETPA', 'ETPA', 'NL', 3600)
    """ETPA - operational: ENERGY TRADING PLATFORM AMSTERDAM. ELECTRONIC PLATFORM TO TRADE SPOT ENERGY CONTRACTS. Location: The Netherlands (NL), Amsterdam, www.etpa.nl."""
    XAMS = MIC('XAMS', 'XAMS', 'NL', 3600)
    """XAMS - operational: EURONEXT - EURONEXT AMSTERDAM. Location: The Netherlands (NL), Amsterdam, www.euronext.com."""
    TNLA = MIC('TNLA', 'XAMS', 'NL', 3600)
    """TNLA - segment of XAMS: EURONEXT - TRADED BUT NOT LISTED AMSTERDAM. Location: The Netherlands (NL), Amsterdam, www.euronext.com."""
    XEUC = MIC('XEUC', 'XAMS', 'NL', 3600)
    """XEUC - segment of XAMS: EURONEXT COM, COMMODITIES FUTURES AND OPTIONS. Location: The Netherlands (NL), Amsterdam, www.euronext.com."""
    XEUE = MIC('XEUE', 'XAMS', 'NL', 3600)
    """XEUE - segment of XAMS: EURONEXT EQF, EQUITIES AND INDICES DERIVATIVES. Location: The Netherlands (NL), Amsterdam, www.euronext.com."""
    XEUI = MIC('XEUI', 'XAMS', 'NL', 3600)
    """XEUI - segment of XAMS: EURONEXT IRF, INTEREST RATE FUTURE AND OPTIONS. Location: The Netherlands (NL), Amsterdam, www.euronext.com."""
    XEMS = MIC('XEMS', 'XEMS', 'NL', 3600)
    """XEMS - operational: EMS EXCHANGE. REGISTERED MARKET FOR SECURITIES, ELECTRONIC TRADING PLATFORM. Location: The Netherlands (NL), S-Hertogenbosch, www.vanlanschot.nl."""
    # -------- Great Britain ------------------------------
    XLDN = MIC('XLDN', 'XLDN', 'GB', 0)
    """XLDN - operational: EURONEXT - EURONEXT LONDON. Location: United Kingdom (GB), London, www.euronext.com."""
    TNLL = MIC('TNLL', 'XLDN', 'GB', 0)
    """TNLL - segment of XLDN: EURONEXT - TRADING FACILITY LONDON. MULTILATERAL  TRADING FACILITY (MTF). Location: United Kingdom (GB), London, www.euronext.com."""
    XSMP = MIC('XSMP', 'XLDN', 'GB', 0)
    """XSMP - segment of XLDN: EURONEXT BLOCK. MULTILATERAL  TRADING FACILITY (MTF). Location: United Kingdom (GB), London, www.euronext.com/blockmtf."""
    ENSY = MIC('ENSY', 'XLDN', 'GB', 0)
    """ENSY - segment of XLDN: EURONEXT SYNAPSE. FIXED INCOME MTF. Location: United Kingdom (GB), London, www.euronext.com."""
    XLBM = MIC('XLBM', 'XLBM', 'GB', 0)
    """XLBM - operational: LONDON BULLION MARKET. Location: United Kingdom (GB), London, www.lbma.org.uk."""
    XLON = MIC('XLON', 'XLON', 'GB', 0)
    """XLON - operational: LONDON STOCK EXCHANGE. Location: United Kingdom (GB), London, www.londonstockexchange.com."""
    XLOD = MIC('XLOD', 'XLON', 'GB', 0)
    """XLOD - segment of XLON: LONDON STOCK EXCHANGE – CURVEGLOBAL MARKETS. LONDON STOCK EXCHANGE DERIVATIVES MARKET (PART OF LONDON STOCK EXCHANGE REGULATED MARKET). Location: United Kingdom (GB), London, www.londonstockexchange.com."""
    XLOM = MIC('XLOM', 'XLON', 'GB', 0)
    """XLOM - segment of XLON: LONDON STOCK EXCHANGE - MTF. DEACTIVATED JAN 2017 UNTIL MARKET LAUNCH. REACTIVATED AUGUST 2017. Location: United Kingdom (GB), London, www.londonstockexchange.com."""
    AIMX = MIC('AIMX', 'XLON', 'GB', 0)
    """AIMX - segment of XLON: LONDON STOCK EXCHANGE - AIM MTF. DEACTIVATED JAN 2017 UNTIL MARKET LAUNCH. AIMX WAS INACTIVE FROM DECEMBER 2007 UNTIL DECEMBER 2016. REACTIVATED AUGUST 2017. Location: United Kingdom (GB), London, www.londonstockexchange.com."""
    XLME = MIC('XLME', 'XLME', 'GB', 0)
    """XLME - operational: LONDON METAL EXCHANGE. Location: United Kingdom (GB), London, www.lme.co.uk."""
    # -------- United States ------------------------------
    XNYM = MIC('XNYM', 'XNYM', 'US', -18000)
    """XNYM - operational: NEW YORK MERCANTILE EXCHANGE. Location: United States of America (US), New York, www.nymex.com."""
    XNYL = MIC('XNYL', 'XNYM', 'US', -18000)
    """XNYL - segment of XNYM: NEW YORK MERCANTILE EXCHANGE - ENERGY MARKETS. ELECTRONIC TRADING PLATFORM FOR ENERGY MARKETS. Location: United States of America (US), New York, www.nymexonlchclearnet.com."""
    XCEC = MIC('XCEC', 'XNYM', 'US', -18000)
    """XCEC - segment of XNYM: COMMODITIES EXCHANGE CENTER. Location: United States of America (US), New York, www.nymex.com."""
    XNYE = MIC('XNYE', 'XNYM', 'US', -18000)
    """XNYE - segment of XNYM: NEW YORK MERCANTILE EXCHANGE - OTC MARKETS. DIVISION OF THE NEW YORK MERCANTILE EXCHANGE - OTC MARKETS (ECM). Location: United States of America (US), New York, www.nymex.com."""
    XNAS = MIC('XNAS', 'XNAS', 'US', -18000)
    """XNAS - operational: NASDAQ - ALL MARKETS. Location: United States of America (US), New York, www.nasdaq.com."""
    XNCM = MIC('XNCM', 'XNAS', 'US', -18000)
    """XNCM - segment of XNAS: NASDAQ CAPITAL MARKET. PREVIOUSLY (2005) NAMED NASDAQ SMALLCAP MARKET.NASDAQ CAPITAL MARKET SECURITY SATISFIES ALL APPLICABLE QUALIFICATION REQUIREMENTS FOR NASDAQ SECURITIES IN RULE 4300 OTHER THAN THOSE APPLICABLE TO NASDAQ NATIONAL MARKET SECURITIES. Location: United States of America (US), New York, www.nasdaq.com."""
    XNDQ = MIC('XNDQ', 'XNAS', 'US', -18000)
    """XNDQ - segment of XNAS: NASDAQ OPTIONS MARKET. Location: United States of America (US), New York, www.nasdaq.com."""
    XNGS = MIC('XNGS', 'XNAS', 'US', -18000)
    """XNGS - segment of XNAS: NASDAQ/NGS (GLOBAL SELECT MARKET). Location: United States of America (US), New York, www.nasdaq.com."""
    XNIM = MIC('XNIM', 'XNAS', 'US', -18000)
    """XNIM - segment of XNAS: NASDAQ INTERMARKET. ELECTRONIC MARKETPLACE COMPRISED OF MULTIPLE BROKER-DEALERS THAT QUOTE AND TRADE SECURITIES LISTED ON NYSE AND AMEX. Location: United States of America (US), New York, www.nasdaq.com."""
    XNMS = MIC('XNMS', 'XNAS', 'US', -18000)
    """XNMS - segment of XNAS: NASDAQ/NMS (GLOBAL MARKET). Location: United States of America (US), New York, www.nasdaq.com."""
    XPBT = MIC('XPBT', 'XNAS', 'US', -18000)
    """XPBT - segment of XNAS: NASDAQ OMX FUTURES EXCHANGE. NASDAQ ACQUIRED THE PHILADELPHIA STOCK EXCHANGE (PHLX). Location: United States of America (US), Philadelphia, www.nasdaqtrader.com."""
    XPHL = MIC('XPHL', 'XNAS', 'US', -18000)
    """XPHL - segment of XNAS: NASDAQ OMX PHLX. NASDAQ ACQUIRED THE PHILADELPHIA STOCK EXCHANGE (PHLX). Location: United States of America (US), Philadelphia, www.phlx.com."""
    XBOS = MIC('XBOS', 'XNAS', 'US', -18000)
    """XBOS - segment of XNAS: NASDAQ OMX BX. NASDAQ OMX HAS ACQUIRED THE BOSTON STOCK EXCHANGE (BSE). Location: United States of America (US), New York, www.nasdaqomxtrader.com."""
    XPHO = MIC('XPHO', 'XNAS', 'US', -18000)
    """XPHO - segment of XNAS: PHILADELPHIA OPTIONS EXCHANGE. Location: United States of America (US), Philadelphia, www.phlx.com."""
    XPOR = MIC('XPOR', 'XNAS', 'US', -28800)
    """XPOR - segment of XNAS: PORTAL. Location: United States of America (US), Washington, www.nasdaqportalmarket.com."""
    PSXD = MIC('PSXD', 'XNAS', 'US', -18000)
    """PSXD - segment of XNAS: NASDAQ PSX. NON-DISPLAYED (DARK) EXECUTIONS. Location: United States of America (US), New York, www.nasdaqtrader.com."""
    XBXO = MIC('XBXO', 'XNAS', 'US', -18000)
    """XBXO - segment of XNAS: NASDAQ OMX BX OPTIONS. ELECTRONIC MARKET FOR TRADING US LISTED DERIVATIVES. Location: United States of America (US), New York, www.nasdaqomxtrader.com."""
    XNFI = MIC('XNFI', 'XNAS', 'US', -18000)
    """XNFI - segment of XNAS: NASDAQ FIXED INCOME TRADING. Location: United States of America (US), New York, www.nasdaq.com."""
    MELO = MIC('MELO', 'XNAS', 'US', -18000)
    """MELO - segment of XNAS: NASDAQ MIDPOINT-ELO (M-ELO). MIDPOINT EXTENDED POINT ORDER (M-ELO). Location: United States of America (US), New York, www.nasdaqtrader.com."""
    XPSX = MIC('XPSX', 'XNAS', 'US', -18000)
    """XPSX - segment of XNAS: NASDAQ OMX PSX. US EQUITIES EXCHANGE. Location: United States of America (US), New York, www.nasdaqtrader.com."""
    NASD = MIC('NASD', 'XNAS', 'US', -18000)
    """NASD - segment of XNAS: NSDQ DARK. DARK POOL. Location: United States of America (US), New York, www.nasdaq.com."""
    XBRT = MIC('XBRT', 'XNAS', 'US', -18000)
    """XBRT - segment of XNAS: BRUT ECN. Location: United States of America (US), New York, www.nasdaqtrader.com."""
    BOSD = MIC('BOSD', 'XNAS', 'US', -18000)
    """BOSD - segment of XNAS: NASDAQ OMX BX DARK. DARK POOL. Location: United States of America (US), New York, www.nasdaqomxtrader.com."""
    XCME = MIC('XCME', 'XCME', 'US', -21600)
    """XCME - operational: CHICAGO MERCANTILE EXCHANGE. Location: United States of America (US), Chicago, www.cme.com."""
    XIOM = MIC('XIOM', 'XCME', 'US', -21600)
    """XIOM - segment of XCME: INDEX AND OPTIONS MARKET. Location: United States of America (US), Chicago, www.cme.com."""
    NYMS = MIC('NYMS', 'XCME', 'US', -18000)
    """NYMS - segment of XCME: CME SWAPS MARKETS (NYMEX). REGISTERED MARKET FOR SWAP EXECUTION  OF ENERGY IN THE US. Location: United States of America (US), New York, www.cmegroup.com."""
    CMES = MIC('CMES', 'XCME', 'US', -21600)
    """CMES - segment of XCME: CME SWAPS MARKETS (CME). REGISTERED MARKET FOR SWAP EXECUTION IN THE US. Location: United States of America (US), Chicago, www.cmegroup.com."""
    CBTS = MIC('CBTS', 'XCME', 'US', -21600)
    """CBTS - segment of XCME: CME SWAPS MARKETS (CBOT). REGISTERED MARKET FOR SWAP EXECUTION IN THE US. Location: United States of America (US), Chicago, www.cmegroup.com."""
    CECS = MIC('CECS', 'XCME', 'US', -18000)
    """CECS - segment of XCME: CME SWAPS MARKETS (COMEX). REGISTERED MARKET FOR SWAP EXECUTION  OF METALS IN THE US. Location: United States of America (US), New York, www.cmegroup.com."""
    FCME = MIC('FCME', 'XCME', 'US', -21600)
    """FCME - segment of XCME: CHICAGO MERCANTILE EXCHANGE (FLOOR). Location: United States of America (US), Chicago, www.cme.com."""
    GLBX = MIC('GLBX', 'XCME', 'US', -21600)
    """GLBX - segment of XCME: CME GLOBEX. Location: United States of America (US), Chicago, www.cme.com."""
    XIMM = MIC('XIMM', 'XCME', 'US', -21600)
    """XIMM - segment of XCME: INTERNATIONAL MONETARY MARKET. Location: United States of America (US), Chicago, www.cme.com."""
    XNYS = MIC('XNYS', 'XNYS', 'US', -18000)
    """XNYS - operational: NEW YORK STOCK EXCHANGE, INC. Location: United States of America (US), New York, www.nyse.com."""
    ALDP = MIC('ALDP', 'XNYS', 'US', -18000)
    """ALDP - segment of XNYS: NYSE ALTERNEXT DARK. DARK POOL. Location: United States of America (US), New York, www.euronext.com/landing/equitiesop-21363-en.html."""
    AMXO = MIC('AMXO', 'XNYS', 'US', -18000)
    """AMXO - segment of XNYS: NYSE AMEX OPTIONS. Location: United States of America (US), New York, www.nyse.com."""
    ARCD = MIC('ARCD', 'XNYS', 'US', -18000)
    """ARCD - segment of XNYS: ARCA DARK. DARK POOL. Location: United States of America (US), New York, www.nyse.com."""
    ARCO = MIC('ARCO', 'XNYS', 'US', -18000)
    """ARCO - segment of XNYS: NYSE ARCA OPTIONS. NYSE ARCA OPTIONS TRADING PLATFORM FROM NYSE EURONEXT. Location: United States of America (US), New York, www.nyse.com."""
    XCHI = MIC('XCHI', 'XNYS', 'US', -21600)
    """XCHI - segment of XNYS: NYSE CHICAGO, INC. Location: United States of America (US), Chicago, www.nyse.com."""
    NYSD = MIC('NYSD', 'XNYS', 'US', -18000)
    """NYSD - segment of XNYS: NYSE DARK. DARK POOL. Location: United States of America (US), New York, www.nyse.com."""
    XCIS = MIC('XCIS', 'XNYS', 'US', -18000)
    """XCIS - segment of XNYS: NYSE NATIONAL, INC. Location: United States of America (US), New York, www.nyse.com."""
    XASE = MIC('XASE', 'XNYS', 'US', -18000)
    """XASE - segment of XNYS: NYSE MKT LLC. NYSE ALTERNEXT HAS CHANGED THEIR NAME TO NYSE AMEX EQUITIES. Location: United States of America (US), New York, www.nyse.com."""
    XNLI = MIC('XNLI', 'XNYS', 'US', -18000)
    """XNLI - segment of XNYS: NYSE LIFFE. Location: United States of America (US), New York, www.nyse.com."""
    ARCX = MIC('ARCX', 'XNYS', 'US', -18000)
    """ARCX - segment of XNYS: NYSE ARCA. Location: United States of America (US), New York, www.nyse.com."""
    CISD = MIC('CISD', 'XNYS', 'US', -18000)
    """CISD - segment of XNYS: NYSE NATIONAL, INC. - DARK. DARK MIC FOR NYSE NATIONAL. Location: United States of America (US), New York, www.nyse.com."""
